# Generated by Django 4.2.23 on 2025-08-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
